### ISSUE TITLE
使用Redis::brPop()过一段时间后会报错

### ISSUE THREAD

**Issue by hisune** [swoft-cloud/swoft#1045]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.8
| PHP version         | 7.2.6,
| Runtime environment | Ubuntu

**Describe the bug**
使用Redis::brPop()过一段时间后会报错，提示重连redis失败

redis配置
```php
    'redis'      => [
        'class'    => RedisDb::class,
        'driver'   => 'phpredis',
        'host'     => '127.0.0.1',
        'port'     => 6379,
        'database' => 0,
        // 'password' => 123,
        'option'        => [
            'serializer' => 0
        ],
    ],
    'redis.pool'     => [
        'class'   => \Swoft\Redis\Pool::class,
        'redisDb' => \bean('redis'),
        'minActive'   => 20,
        'maxActive'   => 50,
        'maxWait'     => 0,
        'maxWaitTime' => 0,
        'maxIdleTime' => 40,
    ],
```

command文件：
```php
<?php declare(strict_types=1);

namespace App\Console\Command;
use Swoft\Console\Annotation\Mapping\Command;
use Swoft\Console\Annotation\Mapping\CommandMapping;
use Swoft\Console\Input\Input;
use Swoft\Redis\Redis;

/**
 * Class TestCommand
 *
 * @Command()
 */
class TestCommand
{
    /**
     * @CommandMapping()
     * @param Input $input
     */
    public function start(Input $input): void
    {
        while (true){
            $pops = Redis::brPop(['test'], 0);
            if($pops){
                var_dump($pops);
            }
        }
    }

}
```
执行：`php bin/swoft test:start`
一段时间后报错：
```
(CONSOLE)Swoft\Redis\Exception\RedisException: Redis command reconnect error(read error on connection to 127.0.0.1:6379)
At /mnt/d/work/git/console/vendor/swoft/redis/src/Connection/Connection.php line 389
Code Trace:
#0 /mnt/d/work/git/console/vendor/swoft/redis/src/Connection/Connection.php(386): Swoft\Redis\Connection\Connection->command('brPop', Array, true)
#1 /mnt/d/work/git/console/vendor/swoft/redis/src/Connection/Connection.php(640): Swoft\Redis\Connection\Connection->command('brPop', Array)
#2 /mnt/d/work/git/console/vendor/swoft/redis/src/Redis.php(182): Swoft\Redis\Connection\Connection->__call('brPop', Array)
#3 /mnt/d/work/git/console/app/Console/Command/AdclicksCommand.php(34): Swoft\Redis\Redis::__callStatic('brPop', Array)
#4 /mnt/d/work/git/console/vendor/swoft/stdlib/src/Helper/PhpHelper.php(54): App\Console\Command\AdclicksCommand->start(Object(Swoft\Console\Input\Input
))
#5 /mnt/d/work/git/console/vendor/swoft/console/src/ConsoleDispatcher.php(85): Swoft\Stdlib\Helper\PhpHelper::call(Array, Object(Swoft\Console\Input\Inp
ut))
#6 /mnt/d/work/git/console/vendor/swoft/console/src/ConsoleDispatcher.php(67): Swoft\Console\ConsoleDispatcher->executeByCo(Object(App\Console\Command\A
dclicksCommand), 'start', Array)
#7 {main}

```

**Comment by hisune** [comment]
已解决，是php.ini的default_socket_timeout配置问题
