### ISSUE TITLE
websocket的消息控制器报错

### ISSUE THREAD

**Issue by roockey** [swoft-cloud/swoft#1101]
> win 7 cygwin
PHP 7.1.16
swoole 4.4.12
测试数据
URL：ws://IP:port/chat  
Message: home.index

```
2019/11/16 14:50:32 [DEBUG] [WorkerId:1, TID:2, CID:2] Message: conn#3 received message: home.index

2019/11/16 14:50:32 [ERROR] [WorkerId:1, TID:2, CID:2] Message: conn#3 error: session information h
as been lost of the SID: 3
2019/11/16 14:50:32 [INFO] [WorkerId:1, TID:2, CID:2] (private)The #SYSTEM send message to the user
 #3. Opcode: 1 Data: session information has been lost of the SID: 3
PHP Fatal error:  Uncaught TypeError: Swoole\WebSocket\Server::push() expects parameter 4 to be int
eger, boolean given in /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WebSo
cketServer.php:124
Stack trace:
#0 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php(124):
 Swoole\WebSocket\Server->push(3, 'session informa...', 1, true)
#1 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php(100):
 Swoft\WebSocket\Server\WebSocketServer->sendTo(3, 'session informa...', 0, 1, true)
#2 /cygdrive/g/stone/learn/swoole/swoft/app/Exception/Handler/WsMessageExceptionHandler.php(47): Sw
oft\WebSocket\Server\WebSocketServer->push(3, 'session informa...')
#3 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WsErrorDispatcher.php(106
): App\Exception\Handler\WsMessageExceptionHandler->handle(Object(Swoft\Exception\SessionException)
, Object(Swoole\WebSocket\Frame))
#4 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-se in /cygdrive/g/stone/learn/swoole
/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php on line 124
PHP Fatal error:  Uncaught ErrorException: Uncaught TypeError: Swoole\WebSocket\Server::push() expe
cts parameter 4 to be integer, boolean given in /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/w
ebsocket-server/src/WebSocketServer.php:124
Stack trace:
#0 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php(124):
 Swoole\WebSocket\Server->push(3, 'session informa...', 1, true)
#1 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php(100):
 Swoft\WebSocket\Server\WebSocketServer->sendTo(3, 'session informa...', 0, 1, true)
#2 /cygdrive/g/stone/learn/swoole/swoft/app/Exception/Handler/WsMessageExceptionHandler.php(47): Sw
oft\WebSocket\Server\WebSocketServer->push(3, 'session informa...')
#3 /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/websocket-server/src/WsErrorDispatcher.php(106
): App\Exception\Handler\WsMessageExceptionHandler->handle(Object(Swoft\Exception\SessionException)
, Object(Swoole\WebSocket\Frame))
#4 /cygdrive/g/stone/learn/swoole/swoft/ in /cygdrive/g/stone/learn/swoole/swoft/vendor/swoft/webso
cket-server/src/WebSocketServer.php on line 124
2019/11/16 14:50:33 [INFO] [WorkerId:-1, TID:-1, CID:-1] WorkerError: exitCode=255, Error worker: w
orkerId=1 workerPid=9752
```

**Comment by inhere** [comment]
`Swoole\WebSocket\Server::push() expects parameter 4 to be int` 这个方法在 4.4.12 有变动，我们兼容下
