### ISSUE TITLE
error!! ---> /usr/local/bin/swoftcli gen:listener demo!

### ISSUE THREAD

**Issue by herenet** [swoft-cloud/swoft#1161]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.12
| PHP version         | 7.2.24
| Runtime environment | Ubuntu

```error report
(CONSOLE)RuntimeException: Template file not exists! File: phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/template/classes/evt-listener.stub
At phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/src/FileRenderer.php line 223
Code Trace:
#0 phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/src/FileRenderer.php(163): SwoftLabs\Devtool\FileRenderer->getTplFilepath()
#1 phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/src/CodeGenerator.php(272): SwoftLabs\Devtool\FileRenderer->render(Array)
#2 phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/src/CodeGenerator.php(204): SwoftLabs\Devtool\CodeGenerator->writeFile(Object(Swoft\Console\Input\Input), Object(Swoft\Console\Output\Output))
#3 phar:///usr/local/bin/swoftcli/vendor/swoftlabs/common-devtool/src/Command/GenCommand.php(352): SwoftLabs\Devtool\CodeGenerator->runInCli(Object(Swoft\Console\Input\Input), Object(Swoft\Console\Output\Output), 'evtListener')
#4 phar:///usr/local/bin/swoftcli/vendor/swoft/console/src/ConsoleDispatcher.php(46): SwoftLabs\Devtool\Command\GenCommand->listener(Object(Swoft\Console\Input\Input), Object(Swoft\Console\Output\Output))
#5 phar:///usr/local/bin/swoftcli/vendor/swoft/console/src/Application.php(209): Swoft\Console\ConsoleDispatcher->dispatch(Array)
#6 phar:///usr/local/bin/swoftcli/vendor/swoft/console/src/Application.php(146): Swoft\Console\Application->doRun('gen:listener')
#7 phar:///usr/local/bin/swoftcli/vendor/swoft/framework/src/Processor/ConsoleProcessor.php(42): Swoft\Console\Application->run()
#8 phar:///usr/local/bin/swoftcli/vendor/swoft/framework/src/Processor/ApplicationProcessor.php(34): Swoft\Processor\ConsoleProcessor->handle()
#9 phar:///usr/local/bin/swoftcli/vendor/swoft/framework/src/SwoftApplication.php(221): Swoft\Processor\ApplicationProcessor->handle()
#10 phar:///usr/local/bin/swoftcli/bin/swoftcli(13): Swoft\SwoftApplication->run()
#11 /usr/local/bin/swoftcli(11): require('phar:///usr/loc...')
#12 {main}
```

**Comment by stelin** [comment]
感谢反馈，2.0.8 修复

**Comment by inhere** [comment]
已修复，等待下个 swoftcli 版本发布
