### ISSUE TITLE
Validator does not recognize the parameters of the GET request.

### ISSUE THREAD

**Issue by heshiweij** [swoft-cloud/swoft#1180]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.3.12
| Runtime environment | CentOS 7

**Describe the bug**
验证组件无法识别 GET 请求的参数
Validator does not recognize the parameters of the GET request.

以下是代码
Here is the code

HomeController.php:
```
 /**
 * Class HomeController
 * @Controller()
 * @Middlewares({
 *   @Middleware(ResponseMiddlewareMiddleware::class)
 * })
 */
class HomeController
{

    /**
     * @RequestMapping("/home", method={"GET"})
     * @Validate(UserValidator::class)
     */
    public function home()
    {
        var_dump(context()->getRequest()->input());
        return context()->getResponse()->withContent('success')->withContentType(ContentType::HTML);
    }
}
```

UserValidator.php
```

/**
 * Class UserValidator
 *
 * @since 2.0
 *
 * @Validator()
 */
class UserValidator
{
    /**
     * @IsString(message="username is required.")
     * @var string
     */
    protected $username;

    /**
     * @IsString(message="password is required.")
     * @var string
     */
    protected $password;
}
```

当发送不带参数的 GET 请求:
When I execute the following code:
```
curl http://127.0.0.1:18306/home
```

响应:
Response:
```
{
    "code": 0,
    "error": "(Swoft\\Validator\\Exception\\ValidatorException) 用户名必须填写",
    "file": "At \/www\/swoft\/vendor\/swoft\/validator\/src\/Rule\/IsStringRule.php line 41",
    "trace": "#0 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(209): Swoft\\Validator\\Rule\\IsStringRule->validate(Array, 'username', Object(Swoft\\Validator\\Annotation\\Mapping\\IsString), NULL)\n#1 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(186): Swoft\\Validator\\Validator->validateDefaultItem(Array, 'username', Object(Swoft\\Validator\\Annotation\\Mapping\\IsString), NULL)\n#2 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(149): Swoft\\Validator\\Validator->validateDefaultValidator(Array, Array, Array, Array)\n#3 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(117): Swoft\\Validator\\Validator->validateValidator(Array, 1, 'App\\\\Validator\\\\U...', Array, Array, Array, Array)\n#4 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Middleware\/ValidatorMiddleware.php(67): Swoft\\Validator\\Validator->validateRequest(Array, Array, Array)\n#5 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\ValidatorMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#6 \/www\/swoft\/app\/Http\/Middleware\/ResponseMiddlewareMiddleware.php(42): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#7 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\ResponseMiddlewareMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#8 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Middleware\/UserMiddleware.php(54): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#9 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#10 \/www\/swoft\/vendor\/swoft\/view\/src\/Middleware\/ViewMiddleware.php(41): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#11 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\View\\Middleware\\ViewMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#12 \/www\/swoft\/app\/Http\/Middleware\/CorsMiddlewareMiddleware.php(45): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#13 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\CorsMiddlewareMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#14 \/www\/swoft\/vendor\/swoft\/session\/src\/SessionMiddleware.php(67): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#15 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Session\\SessionMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#16 \/www\/swoft\/app\/Http\/Middleware\/FavIconMiddleware.php(47): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#17 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\FavIconMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#18 \/www\/swoft\/vendor\/swoft\/http-server\/src\/HttpDispatcher.php(80): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#19 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Swoole\/RequestListener.php(42): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#20 {main}"
}
```

当然，这没问题.
Of course, It's no problem.

但是，我带上参数:
But, i perform request with query parameter:
```shell
curl http://127.0.0.1:18306/home?username=hsw&password=123
```

响应:
Response:
```
{
    "code": 0,
    "error": "(Swoft\\Validator\\Exception\\ValidatorException) 用户名必须填写",
    "file": "At \/www\/swoft\/vendor\/swoft\/validator\/src\/Rule\/IsStringRule.php line 41",
    "trace": "#0 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(209): Swoft\\Validator\\Rule\\IsStringRule->validate(Array, 'username', Object(Swoft\\Validator\\Annotation\\Mapping\\IsString), NULL)\n#1 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(186): Swoft\\Validator\\Validator->validateDefaultItem(Array, 'username', Object(Swoft\\Validator\\Annotation\\Mapping\\IsString), NULL)\n#2 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(149): Swoft\\Validator\\Validator->validateDefaultValidator(Array, Array, Array, Array)\n#3 \/www\/swoft\/vendor\/swoft\/validator\/src\/Validator.php(117): Swoft\\Validator\\Validator->validateValidator(Array, 1, 'App\\\\Validator\\\\U...', Array, Array, Array, Array)\n#4 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Middleware\/ValidatorMiddleware.php(67): Swoft\\Validator\\Validator->validateRequest(Array, Array, Array)\n#5 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\ValidatorMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#6 \/www\/swoft\/app\/Http\/Middleware\/ResponseMiddlewareMiddleware.php(42): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#7 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\ResponseMiddlewareMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#8 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Middleware\/UserMiddleware.php(54): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#9 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#10 \/www\/swoft\/vendor\/swoft\/view\/src\/Middleware\/ViewMiddleware.php(41): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#11 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\View\\Middleware\\ViewMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#12 \/www\/swoft\/app\/Http\/Middleware\/CorsMiddlewareMiddleware.php(45): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#13 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\CorsMiddlewareMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#14 \/www\/swoft\/vendor\/swoft\/session\/src\/SessionMiddleware.php(67): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#15 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Session\\SessionMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#16 \/www\/swoft\/app\/Http\/Middleware\/FavIconMiddleware.php(47): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#17 \/www\/swoft\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\FavIconMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#18 \/www\/swoft\/vendor\/swoft\/http-server\/src\/HttpDispatcher.php(80): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#19 \/www\/swoft\/vendor\/swoft\/http-server\/src\/Swoole\/RequestListener.php(42): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#20 {main}"
}
```

显然，这就有问题了...
The validator does not recognize the parameters of the GET request.

**Comment by inhere** [comment]
需要加上数据来源类型：

```php
 * @Validate(UserValidator::class)
```

改为：

```php
 * @Validate(UserValidator::class, type=ValidateType::GET)
```

**Comment by heshiweij** [comment]
Thank you~
