### ISSUE TITLE
`sendToAll`方法报错。在`HTTP`请求内不能广播`WebSocket`消息吗？

### ISSUE THREAD

**Issue by qq2504021719** [swoft-cloud/swoft#1203]
### 环境
- 1.[HTTP请求正常](http://swoft.plasr.cn/admin/system/peration-log/list)
-  2.WebSocket正常([能和服务器正常通行](http://swoft.plasr.cn/index.html))
- 3.[消息发送API](http://swoft.plasr.cn/home/web-socket-test/send)

### 代码
```
<?php
/**
 * Created by PhpStorm.
 * User: EricPan
 * Date: 2020/1/13
 * Time: 11:27
 */

namespace App\Http\Controller\Home;

use Swoft\Http\Server\Annotation\Mapping\Controller;
use Swoft\Http\Message\Request;
use Swoft\Http\Server\Annotation\Mapping\RequestMapping;
use Swoft\WebSocket\Server\WebSocketServer;

/**
 * webSocket测试
 * Class WebSocketTestController
 * @package App\Http\Controller\Home
 * @Controller("/home/web-socket-test")
 */
class WebSocketTestController
{
    /**
     * 测试消息发送
     * Created by PhpStorm.
     * User: EricPan
     * Date: 2020/1/13
     * Time: 11:32
     *  @RequestMapping(route="send")
     * @param Request $request
     */
    public function send(Request $request)
    {
        $type = $request->input('type',1); // 1全部 2单个
        $fd = $request->input('fd',''); // WebSocket的fd
        $msg = $request->input('msg','默认消息'.mt_rand(1,10000)); // 默认消息
        $ws = new WebSocketServer();

        if($type == 1)
        {
            $ws->sendToAll($msg);
        }
        else if($fd != '')
        {
            $ws->sendTo($fd,$msg);
        }
    }
}
```

### 错误信息
```
{"code":0,"error":"(Error) Call to a member function getClientList() on null","file":"At \/www\/web\/swofttest\/vendor\/swoft\/websocket-server\/src\/WebSocketServer.php line 320","trace":"#0 \/www\/web\/swofttest\/vendor\/swoft\/websocket-server\/src\/WebSocketServer.php(231): Swoft\\WebSocket\\Server\\WebSocketServer->pageEach(Object(Closure), 50)\n#1 \/www\/web\/swofttest\/app\/Http\/Controller\/Home\/WebSocketTestController.php(44): Swoft\\WebSocket\\Server\\WebSocketServer->sendToAll('\\xE9\\xBB\\x98\\xE8\\xAE\\xA4\\xE6\\xB6\\x88\\xE6\\x81\\xAF718...')\n#2 \/www\/web\/swofttest\/vendor\/swoft\/stdlib\/src\/Helper\/PhpHelper.php(54): App\\Http\\Controller\\Home\\WebSocketTestController->send(Object(Swoft\\Http\\Message\\Request))\n#3 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/Middleware\/DefaultMiddleware.php(75): Swoft\\Stdlib\\Helper\\PhpHelper::call(Array, Object(Swoft\\Http\\Message\\Request))\n#4 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\DefaultMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#5 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/Middleware\/ValidatorMiddleware.php(50): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#6 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\ValidatorMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#7 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/Middleware\/UserMiddleware.php(54): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#8 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#9 \/www\/web\/swofttest\/vendor\/swoft\/view\/src\/Middleware\/ViewMiddleware.php(41): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#10 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): Swoft\\View\\Middleware\\ViewMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#11 \/www\/web\/swofttest\/app\/Http\/Middleware\/FavIconMiddleware.php(45): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#12 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/RequestHandler.php(73): App\\Http\\Middleware\\FavIconMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#13 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/HttpDispatcher.php(80): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#14 \/www\/web\/swofttest\/vendor\/swoft\/http-server\/src\/Swoole\/RequestListener.php(42): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#15 {main}"}
```

**Comment by inhere** [comment]
你这使用完全错误。只是new一个ws server对象，没啥没用啊。。。。

要想http里可以直接使用ws server，应该在启动 ws server时同时启用http功能。

http://swoft.io/docs/2.x/zh-CN/websocket-server/config.html#%E5%90%AF%E7%94%A8http%E8%AF%B7%E6%B1%82%E5%A4%84%E7%90%86

**Comment by qq2504021719** [comment]
ok，我去试试。谢谢~

**Comment by qq2504021719** [comment]
@inhere 
#### 上次你回复我之后我在wsServer里面配置了`SwooleEvent::REQUEST => bean(RequestListener::class),`我记得是可以了。但今天我重启服务之后就不行了。

#### 在Http的控制器里面调用websocket
```php
    /**
     * 测试消息发送
     * Created by PhpStorm.
     * User: EricPan
     * Date: 2020/1/13
     * Time: 11:32
     *  @RequestMapping(route="send")
     * @param Request $request
     */
    public function send(Request $request)
    {
        $type = $request->input('type',1); // 1全部 2单个
        $fd = $request->input('fd',''); // WebSocket的fd
        $msg = $request->input('msg','默认消息'.mt_rand(1,10000)); // 默认消息
        $ws = new WebSocketServer();

        if($type == 1)
        {
//            \server()->sendToAll($msg);
            $ws->sendToAll($msg);
        }
        else if($fd != '')
        {
            $ws->sendTo($fd,$msg);
        }
        return '发送消息:'.$msg;

    }
```

#### 我在配置文件里面配置和开启http请求,还是会有下面的报错
``` php
    'wsServer'   => [
        'class'   => WebSocketServer::class,
        'port' => 18308,
        'on'      => [
            // 加上如下一行，开启处理http请求
            SwooleEvent::REQUEST => bean(RequestListener::class),
        ],
        'debug' => env('SWOFT_DEBUG', 0),
        /* @see WebSocketServer::$setting */
        'setting' => [
            'log_file' => alias('@runtime/swoole.log'),
        ],
    ],
```
#### 报错

```
{"code":0,"error":"(Error) Call to a member function getClientList() on null","file":"At \/www\/web\/swofttest\/vendor\/swoft\/websocket-server\/src\/WebSocketServer.php
```

**Comment by inhere** [comment]
之前就说过呀。

- 不要new WebSocketServer对象使用。这样只是一个空对象
- 直接使用 `server()` 获取swoft提供的WebSocketServer对象

**Comment by qq2504021719** [comment]
> 在`HTTP`请求内调用`WebSocket`，`WebSocket`是正常连接的

### `sendTo`是可以发送消息，前端`3`也能收到后台发送的消息
``` php
server()->sendTo(3,$msg);
```

### `sendToAll`就报错了
```php
server()->sendToAll($msg);
```

#### 报错
```
App\Exception\Handler\HttpExceptionHandler:handle(44) Argument 1 passed to Swoft\Log\Helper\Log::info() must be of the type string, array given, called in /www/web/swofttest/vendor/swoft/websocket-server/src/WebSocketServer.php on line 321

```

**Comment by inhere** [comment]
多少版本的

**Comment by qq2504021719** [comment]
2.0.0
