### ISSUE TITLE
Pool error is Create connection error

### ISSUE THREAD

**Issue by Kyourcn** [swoft-cloud/swoft#1211]
在控制台看到出现了这个报错，不知道会不会有影响

```text
PHP Fatal error:  Uncaught Swoft\Db\Exception\DbException: Pool error is Create connection error(SQLSTATE[HY000] [2006] MySQL server has gone away) file(/data/www/yunan_sw/vendor/swoft/db/src/Connector/AbstractConnector.php) line (45) file=/data/www/yunan_sw/vendor/swoft/connection-pool/src/AbstractPool.php line=250 in /data/www/yunan_sw/vendor/swoft/db/src/DB.php:81
Stack trace:
#0 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(3355): Swoft\Db\DB::connection('db.pool')
#1 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2370): Swoft\Db\Query\Builder->getConnection()
#2 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2354): Swoft\Db\Query\Builder->runSelect()
#3 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2838): Swoft\Db\Query\Builder->Swoft\Db\Query\{closure}()
#4 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2355): Swoft\Db\Query\Builder->onceWithColumns(Array, Object(Closure))
#5 /data/www/yunan_sw/app/Crontab/CronDevicesTask.php(47): Swoft\Db\Query\Builder->get()
#6 /data/ in /data/www/yunan_sw/vendor/swoft/db/src/DB.php on line 81
PHP Fatal error:  Uncaught ErrorException: Uncaught Swoft\Db\Exception\DbException: Pool error is Create connection error(SQLSTATE[HY000] [2006] MySQL server has gone away) file(/data/www/yunan_sw/vendor/swoft/db/src/Connector/AbstractConnector.php) line (45) file=/data/www/yunan_sw/vendor/swoft/connection-pool/src/AbstractPool.php line=250 in /data/www/yunan_sw/vendor/swoft/db/src/DB.php:81
Stack trace:
#0 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(3355): Swoft\Db\DB::connection('db.pool')
#1 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2370): Swoft\Db\Query\Builder->getConnection()
#2 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2354): Swoft\Db\Query\Builder->runSelect()
#3 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2838): Swoft\Db\Query\Builder->Swoft\Db\Query\{closure}()
#4 /data/www/yunan_sw/vendor/swoft/db/src/Query/Builder.php(2355): Swoft\Db\Query\Builder->onceWithColumns(Array, Object(Closure))
#5 /data/www/yunan_sw/app/Crontab/CronDevicesTask.php(47): Swoft\Db\Query in /data/www/yunan_sw/vendor/swoft/db/src/DB.php on line 81
```

**Comment by sakuraovq** [comment]
连接超时了 是不是 是用的默认连接池配置吗
