### ISSUE TITLE
Failed opening required '/tmp/HttpHandleBean_PROXY_5e8455cdd6887.php' (include_path='.:/usr/share/pear7:/usr/share/php7') 

### ISSUE THREAD

**Issue by Hetystars** [swoft-cloud/swoft#1246]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.8
| Swoole version      | 4.1.10
| PHP version         | 7.1
| Runtime environment | CentOS 7

**Describe the bug**

```
PHP Warning:  Uncaught ErrorException: require(/tmp/HttpHandleBean_PROXY_5e8455cdd6887.php): failed to open stream: No such file or directory in project/vendor/swoft/proxy/src/Proxy.php:54
Stack trace:
#0 project/vendor/swoft/proxy/src/Proxy.php(54): Swoft\Error\DefaultErrorDispatcher->handleError(2, 'require(/tmp/Ht...', '/var/www/http/a...', 54, Array)
#1 project/vendor/swoft/proxy/src/Proxy.php(54): require()
#2 project/vendor/swoft/aop/src/Proxy.php(37): Swoft\Proxy\Proxy::newClassName('App\\Bean\\Elasti...', Object(Swoft\Aop\Ast\Visitor\ProxyVisitor))
#3 project/vendor/swoft/framework/src/BeanHandler.php(109): Swoft\Aop\Proxy::newClassName('App\\Bean\\Elasti...')
#4 project/vendor/swoft/bean/src/Container.php(914): Swoft\BeanHandler->classProxy('App\\Bean\\Elasti...')
#5 project/vendor/swoft/bean/src/Container.php(869): Swoft\Bean\Container->newBean('httpHandleBean', '7328')
#6 /var/www/ in project/vendor/swoft/proxy/src/Proxy.php on line 54
PHP Fatal error:  Swoft\Proxy\Proxy::newClassName(): Failed opening required '/tmp/HttpHandleBean_PROXY_5e8455cdd6887.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in project/vendor/swoft/proxy/src/Proxy.php on line 54
PHP Fatal error:  Uncaught ErrorException: Swoft\Proxy\Proxy::newClassName(): Failed opening required '/tmp/HttpHandleBean_PROXY_5e8455cdd6887.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in project/vendor/swoft/proxy/src/Proxy.php:54
Stack trace:
#0 project/vendor/swoft/error/src/DefaultErrorDispatcher.php(64): Swoft\Error\DefaultErrorDispatcher->handleError(64, 'Swoft\\Proxy\\Pro...', '/var/www/http/a...', 54)
#1 [internal function]: Swoft\Error\DefaultErrorDispatcher->Swoft\Error\{closure}()
#2 {main}
  thrown in project/vendor/swoft/proxy/src/Proxy.php on line 54
[2020-04-01 08:50:21 *29960.1]  ERROR   php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: Swoft\Proxy\Proxy::newClassName(): Failed opening required '/tmp/HttpHandleBean_PROXY_5e8455cdd6887.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in project/vendor/swoft/proxy/src/Proxy.php:54
Stack trace:
#0 project/vendor/swoft/error/src/DefaultErrorDispatcher.php(64): Swoft\Error\DefaultErrorDispatcher->handleError(64, 'Swoft\\Proxy\\Pro...', '/var/www/http/a...', 54)
#1 [internal function]: Swoft\Error\DefaultErrorDispatcher->Swoft\Error\{closure}()
#2 {main}
  thrown in project/vendor/swoft/proxy/src/Proxy.php on line 54
[2020-04-01 08:50:21 $4828.0]   WARNING swManager_check_exit_status: worker#1[pid=29960] abnormal exit, status=255, signal=0
```

磁盘空间足够，qps 40左右
所涉及的bean为request bean,每次请求均会产生相应的代理类
/tmp/目录下无相应的代理类文件
初步定位问题为
swoft\vendor\swoft\rpc-client\src\Proxy.php文件中生成代理类文件名在并发量很高的情况下存在重名的情况，uniqid方法当前时间处于同一微秒时，会产生相同的ID

```php

    /**
     * @param string $className
     *
     * @return string
     * @throws RpcClientException
     * @throws ProxyException
     */
    public static function newClassName(string $className): string
    {
        if (!interface_exists($className)) {
            throw new RpcClientException(
                sprintf('`@var` for `@Reference` must be exist interface!')
            );
        }

        $proxyId   = sprintf('IGNORE_%s', Str::getUniqid());
        $visitor   = new ProxyVisitor($proxyId);
        $className = BaseProxy::newClassName($className, $visitor);
        return $className;
    }
    /**
     * @param string $prefix
     * @param bool   $moreEntropy
     *
     * @return string
     */
    public static function getUniqid(string $prefix = "", bool $moreEntropy = false): string
    {
        $uniqid = uniqid($prefix, $moreEntropy);
        $uniqid = str_replace('.', '', $uniqid);
        return $uniqid;
    }
```
**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by Hetystars** [comment]
@stelin 有空帮看一下么，生产环境每小时大约会有5-10个报错出现，影响正常业务流程

**Comment by Hetystars** [comment]
@inhere v2.0.9 有具体的时间安排么,是否能现在更新一下Swoft\Aop\Ast\Visitor\ProxyVisitor类中生成proxyId的方法，给uniqid方法增加more_entropy=true参数

**Comment by inhere** [comment]
@Hetystars  今天发个版本

**Comment by inhere** [comment]
@Hetystars 你是用 AOP 切了requestBean 吗？

**Comment by inhere** [comment]
发了新版本，你再观察下
