### ISSUE TITLE
User process fail(/home/www/server/vendor/swoft/framework/src/Context/Context.php context information has been lost of the coID: -1 50)!

### ISSUE THREAD

**Issue by JoyYin-99** [swoft-cloud/swoft#1347]
[ERROR] User process fail(/home/www/server/vendor/swoft/framework/src/Context/Context.php context information has been lost of the coID: -1 50)!

Fatal error: Uncaught TypeError: Return value of Swoft\Event\Manager\EventManager::trigger() must implement interface Swoft\Event\EventInterface, null returned in /home/www/server/vendor/swoft/event/src/Manager/EventManager.php:315
Stack trace:
#0 /home/www/server/vendor/swoft/framework/src/Swoft.php(178): Swoft\Event\Manager\EventManager->trigger('swoft.process.u...', NULL, Array)
#1 /home/www/server/vendor/swoft/process/src/Listener/AddProcessListener.php(81): Swoft::trigger('swoft.process.u...')
#2 {main}
  thrown in /home/www/server/vendor/swoft/event/src/Manager/EventManager.php on line 315

**Comment by JoyYin-99** [comment]
每隔一段时间，就会报一次这个错误，但是还没定位到是怎么触发的，求助一下

**Comment by inhere** [comment]
swoft，swoole 版本呢

**Comment by JoyYin-99** [comment]
Version: 2.0.9
