### ISSUE TITLE
server didnt response

### ISSUE THREAD

**Issue by mhf-ir** [swoft-cloud/swoft#254]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.5
| Swoole version      | 2.2.0
| PHP version         | 7.2.5
| Runtime environment | Docker (Ubuntu base)

server is run base on `composer create-project swoft/swoft swoft`
after copy this .env file:
```
# Server
PFILE=/tmp/swoft.pid
PNAME=php-swoft
TCPABLE=false
CRONABLE=false
AUTO_RELOAD=false
AUTO_REGISTER=false

# HTTP
HTTP_HOST=0.0.0.0
HTTP_PORT=80
HTTP_MODE=SWOOLE_PROCESS
HTTP_TYPE=SWOOLE_SOCK_TCP
```

running server:
```
root@aasaam-swoole:/app/var/tmp/swoft# php bin/swoft server:start 
                         Server Information                      
********************************************************************
* HTTP | host: 0.0.0.0, port: 80, type: 1, worker: 1, mode: 3
* TCP  | host: 0.0.0.0, port: 8099, type: 1, worker: 1 (Disabled)
********************************************************************
Server has been started. (master PID: 21522, manager PID: 21523)
You can use CTRL + C to stop run.
```

curl didnot respone:
```
root@aasaam-swoole:/app/var/tmp/swoft# curl -m 4 -v http://localhost/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Operation timed out after 4001 milliseconds with 0 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 4001 milliseconds with 0 bytes received
```

**Comment by inhere** [comment]
running:

```text
root@testcontainer:/app/var/tmp/swoft# php bin/swoft server:start 
```

usage:

```text
root@aasaam-swoole:/app/var/tmp/swoft# curl -m 4 -v http://localhost/
```

Are `root@testcontainer` and `root@aasaam-swoole` in the same container?

**Comment by mhf-ir** [comment]
sorry for wrong paste it's not a mistake ...
![Testing env](https://i.imgur.com/11g09Fr.png "Testing env")

**Comment by daydaygo** [comment]
in my env all is fine. have you try the [Dockerfile](https://github.com/swoft-cloud/swoft/blob/master/Dockerfile) in the project?

![image](https://user-images.githubusercontent.com/3986303/40619149-8e22578a-62c6-11e8-9005-59cffb107d23.png)

**Comment by mhf-ir** [comment]
it's seems one different i just miss `--enable-coroutine` for swoole that's my image:

https://github.com/AASAAM/aasaam-app/blob/php7.2/Dockerfile#L85

maybe just for that i will test that

**Comment by mhf-ir** [comment]
is database require for hello world ?
```
# php bin/swoft app:check
[Semantical Error] Couldn't find constant Swoft\Event\AppEvent::TRANSACTION_RELEASE, class Swoft\Db\Event\Listeners\TransactionReleaseListener.
Trace:
#0 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php(101): Doctrine\Common\Annotations\AnnotationException::semanticalError('Couldn't find c...')
#1 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(973): Doctrine\Common\Annotations\AnnotationException::semanticalErrorConstants('Swoft\\Event\\App...', 'class Swoft\\Db\\...')
#2 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1039): Doctrine\Common\Annotations\DocParser->Constant()
#3 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1020): Doctrine\Common\Annotations\DocParser->PlainValue()
#4 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(874): Doctrine\Common\Annotations\DocParser->Value()
#5 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(859): Doctrine\Common\Annotations\DocParser->Values()
#6 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(770): Doctrine\Common\Annotations\DocParser->MethodCall()
#7 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#8 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#9 /app/var/tmp/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(222): Doctrine\Common\Annotations\DocParser->parse('/**\n * Transact...', 'class Swoft\\Db\\...')
#10 /app/var/tmp/swoft/vendor/swoft/framework/src/Bean/Resource/AnnotationResource.php(138): Doctrine\Common\Annotations\AnnotationReader->getClassAnnotations(Object(ReflectionClass))
#11 /app/var/tmp/swoft/vendor/swoft/framework/src/Bean/Resource/AnnotationResource.php(114): Swoft\Bean\Resource\AnnotationResource->parseBeanAnnotations('Swoft\\Db\\Event\\...')
#12 /app/var/tmp/swoft/vendor/swoft/framework/src/Bean/Container.php(128): Swoft\Bean\Resource\AnnotationResource->getDefinitions()
#13 /app/var/tmp/swoft/vendor/swoft/framework/src/Bean/BeanFactory.php(55): Swoft\Bean\Container->autoloadWorkerAnnotation()
#14 /app/var/tmp/swoft/vendor/swoft/console/src/Router/HandlerAdapter.php(129): Swoft\Bean\BeanFactory::reload()
#15 /app/var/tmp/swoft/vendor/swoft/console/src/Router/HandlerAdapter.php(111): Swoft\Console\Router\HandlerAdapter->beforeCommand('Swoft\\Devtool\\C...', 'check', false)
#16 /app/var/tmp/swoft/vendor/swoft/console/src/Router/HandlerAdapter.php(38): Swoft\Console\Router\HandlerAdapter->executeCommand(Object(AppCommand_5b0c31631168f), 'check', false, Array)
#17 /app/var/tmp/swoft/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Router\HandlerAdapter->doHandler(Array)
#18 /app/var/tmp/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Router\HandlerAdapter), 'doHandler', Array)
#19 /app/var/tmp/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('doHandler', Array)
#20 /app/var/tmp/swoft/vendor/swoft/console/src/Command.php(77): HandlerAdapter_5b0c316311609->doHandler(Array)
#21 /app/var/tmp/swoft/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Command->run()
#22 /app/var/tmp/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Command), 'run', Array)
#23 /app/var/tmp/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('run', Array)
#24 /app/var/tmp/swoft/vendor/swoft/console/src/Console.php(30): Command_5b0c31631157c->run()
#25 /app/var/tmp/swoft/bin/swoft(5): Swoft\Console\Console->run()
#26 {main}
```

**Comment by inhere** [comment]
this is `swoft/db:v1.1.12` 

https://github.com/swoft-cloud/swoft-db/blob/97c4d49c0f1e7c7156b9e6e2f5e82e8b5a62ee32/src/Event/Listeners/ResourceReleaseBeforeListener.php#L21-L29

**Comment by mhf-ir** [comment]
so what's the problem ? how can i solve it ?
How can i write hello world ? the documentation is so week :(

**Comment by inhere** [comment]
maybe you should run `composer up` in the project dir.
try again :)
