### ISSUE TITLE
如何在websocket的控制器中使用中间件?

### ISSUE THREAD

**Issue by JOSEFAzyq** [swoft-cloud/swoft#303]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | x.y.z
| Swoole version      | 2.2
| PHP version         | 7.1
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

在httpcontroller下可以正常使用session()
但是在websocket下使用session()则报

PHP Fatal error:  Uncaught TypeError: Return value of Swoft\Session\SessionManager::getSession() must implement interface Swoft\Session\SessionInterface, null returned in /Applications/MAMP/htdocs/swoft/vendor/swoft/session/src/SessionManager.php:102

```php
PHP Fatal error:  Uncaught TypeError: Return value of Swoft\Session\SessionManager::getSession() must implement interface Swoft\Session\SessionInterface, null returned in /Applications/MAMP/htdocs/swoft/vendor/swoft/session/src/SessionManager.php:102
Stack trace:
#0 /Applications/MAMP/htdocs/swoft/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Session\SessionManager->getSession()
#1 /Applications/MAMP/htdocs/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Session\SessionManager), 'getSession', Array)
#2 /Applications/MAMP/htdocs/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(23): Swoft\Proxy\Handler\AopHandler->invoke('getSession', Array)
#3 /Applications/MAMP/htdocs/swoft/vendor/swoft/session/src/Helper/Functions.php(12): SessionManager_5b3c9783a3f40->getSession()
#4 /Applications/MAMP/htdocs/swoft/app/WebSocket/EchoController.php(39): session()
#5 /Applications/MAMP/htdocs/swoft/vendor/swoft/framework/src/Aop
```

**Comment by huangzhhui** [comment]
WebSocket 暂不支持中间件机制
