### ISSUE TITLE
Swoft生成corefile问题及进程卡死

### ISSUE THREAD

**Issue by nandychen** [swoft-cloud/swoft#314]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.6
| Swoole version      | 4.0.0
| PHP version         | 7.2.6
| Runtime environment | gcc version 4.8.2 20140120 (Red Hat 4.8.2-16)

**Details**

> 使用场景如下：
1. .env配置如下
//Swoole Settings
WORKER_NUM=4
MAX_REQUEST=100000
DAEMONIZE=0
DISPATCH_MODE=2
TASK_IPC_MODE=2
MESSAGE_QUEUE_KEY=1879052289
TASK_TMPDIR=/tmp/
LOG_FILE=@runtime/logs/swoole.log
TASK_WORKER_NUM=4
PACKAGE_MAX_LENGTH=4096
OPEN_HTTP2_PROTOCOL=false
SSL_CERT_FILE=/path/to/ssl_cert_file
SSL_KEY_FILE=/path/to/ssl_key_file
2. 服务启动后开启异步task，里面while轮询http请求外部服务拉取数据。
3. 运行一段时间后出现corefile内容如下：

```
#0  swMutex_create (lock=0x7fffebd17198, use_in_process=1) at /data/source_code/swoole-4.0.0/src/lock/Mutex.c:27
27	    bzero(lock, sizeof(swLock));
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-13.el6.x86_64 freetype-2.3.11-6.el6_2.9.x86_64 glibc-2.12-1.149.tl1.5.x86_64 keyutils-libs-1.4-3.el6.x86_64 krb5-libs-1.9-22.el6_2.1.x86_64 libcom_err-1.41.12-11.el6.x86_64 libcurl-7.19.7-53.el6_9.x86_64 libgcc-4.4.6-4.tl1.x86_64 libgcrypt-1.4.5-9.el6_2.2.x86_64 libgpg-error-1.7-4.el6.x86_64 libidn-1.18-2.el6.x86_64 libpng-1.2.49-1.el6_2.x86_64 libselinux-2.0.94-5.2.el6.x86_64 libssh2-1.4.2-2.tl1.1.x86_64 libstdc++-4.4.6-4.tl1.x86_64 libxml2-2.7.6-4.el6_2.4.x86_64 libxslt-1.1.26-2.el6.x86_64 nspr-4.13.1-1.tl1.x86_64 nss-3.28.4-4.tl1.x86_64 nss-softokn-freebl-3.14.3-23.3.tl1.x86_64 nss-util-3.28.4-1.tl1.x86_64 openldap-2.4.23-20.el6.x86_64 openssl-1.0.1e-48.tl1.5.x86_64
(gdb) bt
#0  swMutex_create (lock=0x7fffebd17198, use_in_process=1) at /data/source_code/swoole-4.0.0/src/lock/Mutex.c:27
#1  0x00007ffff18932ad in zim_swoole_lock___construct (execute_data=0x7ffff07cad00, return_value=0x7fffec10cf00) at /data/source_code/swoole-4.0.0/swoole_lock.c:137
#2  0x00000000008d53d4 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (execute_data=0x7ffff07cac30) at /data/source_code/php-7.2.6/Zend/zend_vm_execute.h:907
#3  0x00000000008a17d8 in execute_ex (ex=<value optimized out>) at /data/source_code/php-7.2.6/Zend/zend_vm_execute.h:59723
#4  0x00007ffff189d10f in php_coro_create (php_arg=<value optimized out>) at /data/source_code/swoole-4.0.0/swoole_coroutine.cc:176
#5  0x00007ffff19114bb in swoole::Context::context_func (arg=0x15f09f0) at /data/source_code/swoole-4.0.0/src/coroutine/context.cc:66
#6  0x00007ffff193adc1 in make_fcontext () at /data/source_code/swoole-4.0.0/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#7  0x0000000000000000 in ?? ()

```

> 上面第2步是在登录业务逻辑处理完后开始调用的异步task

```
Task::deliver('message', 'listen', [$uuid], Task::TYPE_ASYNC);
```

> 异步task注解及主要片段
```
/**
 * Date: 2018/6/27
 * Time: 11:29
 *
 * @Task("message")
 */
class MessageTask{}
```

```
public function listen(string $uuid)
{        
        try {
            //init logic
            while (true) {
                //http request external service
                sleep(1);
             }
        } catch(\Exception $e) {}
}
```

4. 另外，当上面task由于外部服务登录态会话过期退出while循环后，本服务内manager进程貌似多出1个，其他进程都在，但是再重新发起请求时没有响应，貌似处于卡死状态，php bin/swoft restart服务重启失败，得kill -9后再重启才正常。

**Comment by huangzhhui** [comment]
请更新 Swoole 至 4.0.2 版本，如果问题依旧，提供一个可复原的Demo

**Comment by huangzhhui** [comment]
暂时先关掉此 issue 了，如果问题依旧，提供一个可复原的 Demo 后 reopen 此 issue
