### ISSUE TITLE
运行例子报错 PHP Fatal error:  Uncaught InvalidArgumentException: the name of bean 不存在， name=lineFormate in /home/vagrant/Code/swoft/vendor/swoft/framework/src/Bean/Container.php:71

### ISSUE THREAD

**Issue by hooklife** [swoft-cloud/swoft#43]
```
[2017-11-17 08:24:35 *16581.0]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught InvalidArgumentException: the name of bean 不存在， name=lineFormate in /home/vagrant/Code/swoft/vendor/swoft/framework/src/Bean/Container.php:70
Stack trace:
#0 /home/vagrant/Code/swoft/vendor/swoft/framework/src/Bean/Container.php(277): Swoft\Bean\Container->get('lineFormate')
#1 /home/vagrant/Code/swoft/vendor/swoft/framework/src/Bean/Container.php(186): Swoft\Bean\Container->injectProperties(Object(Swoft\Log\FileHandler), Array, Array)
#2 /hom
```

**Comment by huangzhhui** [comment]
你应该是运行着旧的代码，执行一下git pull 和 composer update
