### ISSUE TITLE
php7.0运行时 Swoft\Web\Response 报错

### ISSUE THREAD

**Issue by clearair** [swoft-cloud/swoft#47]
嗨, 在我的php7.0环境下试运行，发现请求响应时终端会输出
```
PHP Fatal error:  Uncaught TypeError: Return value of Swoft\Web\Response::send() must be an instance of Swoft\Web\void, none returned in /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Web/Response.php:179
Stack trace:
#0 /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Web/Application.php(69): Swoft\Web\Response->send()
#1 /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Server/HttpServer.php(66): Swoft\Web\Application->doRequest(Object(swoole_http_request), Object(swoole_http_response))
#2 [internal function]: Swoft\Server\HttpServer->onRequest(Object(swoole_http_request), Object(swoole_http_response))
#3 /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Server/HttpServer.php(55): swoole_http_server->start()
#4 /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Console/Command/ServerController.php(125): Swoft\Server\HttpServer->start()
#5 /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Helper/PhpHelper.php(50): Swoft\Console\Command\ServerController->startComma in /home/quzhi/Code/zpjinfu-service/vendor/swoft/framework/src/Web/Response.php on line 179
```

我查看后发现 send方法定义了一个 void类型返回值， 但是php7.0貌似并不支持返回void类型
难道这个项目一定要用php7.1+吗？

**Comment by huangzhhui** [comment]
已经修复了，因为我们团队里面的成员都是使用7.1来开发的，可能有些语法很自然的就写上了
