### ISSUE TITLE
配置主从开启事务报错

### ISSUE THREAD

**Issue by Longjianghu** [swoft-cloud/swoft#481]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 4.2.9
| PHP version         | PHP 7.2.10 (cli)
| Runtime environment | Docker etc.

**Details**

配置主从开启事务报错

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
#0 /data/vendor/swoft/framework/src/Aop/Aop.php(57): App\Models\Logic\DingTalkLogic->updateDingTalkUser('{"user_id":"011...')
#1 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(App\Models\Logic\DingTalkLogic), 'updateDingTalkU...', Array)
#2 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(17): Swoft\Proxy\Handler\AopHandler->invoke('updateDingTalkU...', Array)
#3 /data/app/Tasks/DingTalkTask.php(52): DingTalkLogic_5c0de3f36b8b1->updateDingTalkUser('{"user_id":"011...')
#4 /data/vendor/swoft/framework/src/Aop/Aop.php(57): App\Tasks\DingTalkTask->dingTalkUser('{"user_id":"011...')
#5 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(App\Tasks\DingTalkTask), 'dingTalkUser', Array)
#6 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('dingTalkUser', Array)
#7 /data/vendor/swoft/framework/src/Helper/PhpHelper.php(47): DingTalkTask_5c0de3f390c9a->dingTalkUser('{"user_id":"011...')
#8 /data/vendor/swoft/task/src/TaskExecutor.php(70): Swoft\Helper\PhpHelper::call(Array, Array)
#9 /data/vendor/swoft/task/src/TaskExecutor.php(50): Swoft\Task\TaskExecutor->runSyncTask(Object(DingTalkTask_5c0de3f390c9a), 'dingTalkUser', Array, '', 0, 'dingTalk', 'async')
#10 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Task\TaskExecutor->run(Array)
#11 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Task\TaskExecutor), 'run', Array)
#12 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('run', Array)
#13 /data/vendor/swoft/task/src/Bootstrap/Listeners/TaskEventListener.php(43): TaskExecutor_5c0de3f3b2214->run('a:6:{s:4:"name"...')
#14 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Task\Bootstrap\Listeners\TaskEventListener->onTask(Object(Swoole\Http\Server), 1373, 0, 'a:6:{s:4:"name"...')
#15 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Task\Bootstrap\Listeners\TaskEventListener), 'onTask', Array)
#16 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('onTask', Array)
#17 [internal function]: TaskEventListener_5c0de315d6310->onTask(Object(Swoole\Http\Server), 1373, 0, 'a:6:{s:4:"name"...')
#18 /data/vendor/swoft/http-server/src/Http/HttpServer.php(55): Swoole\Server->start()
#19 /data/vendor/swoft/http-server/src/Command/ServerCommand.php(74): Swoft\Http\Server\Http\HttpServer->start()
#20 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Http\Server\Command\ServerCommand->start()
#21 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Http\Server\Command\ServerCommand), 'start', Array)
#22 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('start', Array)
#23 /data/vendor/swoft/framework/src/Helper/PhpHelper.php(47): ServerCommand_5c0de315d59ab->start()
#24 /data/vendor/swoft/console/src/Router/HandlerAdapter.php(112): Swoft\Helper\PhpHelper::call(Array, Array)
#25 /data/vendor/swoft/console/src/Router/HandlerAdapter.php(38): Swoft\Console\Router\HandlerAdapter->executeCommand(Object(ServerCommand_5c0de315d59ab), 'start', true, Array)
#26 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Router\HandlerAdapter->doHandler(Array)
#27 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Router\HandlerAdapter), 'doHandler', Array)
#28 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('doHandler', Array)
#29 /data/vendor/swoft/console/src/Command.php(77): HandlerAdapter_5c0de315d554b->doHandler(Array)
#30 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Command->run()
#31 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Command), 'run', Array)
#32 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('run', Array)
#33 /data/vendor/swoft/console/src/Console.php(30): Command_5c0de315d54ae->run()
#34 /data/bin/swoft(5): Swoft\Console\Console->run()
#35 {main}
```

**Comment by huangzhhui** [comment]
请提供具体的配置，以及操作的代码，注意脱敏
