### ISSUE TITLE
在 web socket onopen 里 调用了 一个 静态的 connect 方法无法使用redis 容器

### ISSUE THREAD

**Issue by yanwuguangjun** [swoft-cloud/swoft#533]
/**
     * @param Server $server
     * @param Request $request
     * @param int $fd
     * @throws \Swoft\Db\Exception\DbException
     */
    public static function connect(Server $server, Request $request, int $fd)
    {
        $get = $request->getSwooleRequest()->get;

        $id = $get['id'];

        /** @var Redis $red */
        $red = App::getBean("IM");

        $red->hSet('FD', $id, $fd);

//如果初始化容器一下 会报错
PHP Fatal error:  Uncaught InvalidArgumentException: Bean Swoft\Aop\Aop not exist in /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Bean/Container.php:75
Stack trace:
#0 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Bean/BeanFactory.php(76): Swoft\Bean\Container->get('Swoft\\Aop\\Aop')
#1 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Core/ApplicationContext.php(86): Swoft\Bean\BeanFactory::getBean('Swoft\\Aop\\Aop')
#2 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/App.php(124): Swoft\Core\ApplicationContext::getBean('Swoft\\Aop\\Aop')
#3 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Helper/Functions.php(97): Swoft\App::getBean('Swoft\\Aop\\Aop')
#4 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(41): bean('Swoft\\Aop\\Aop')
#5 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('__destruct', Array)
#6 /home/ubuntu/game_console/swoft/vendor/ in /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Bean/Container.php on line 75
[2019-01-13 22:56:55 *18151.0]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught InvalidArgumentException: Bean Swoft\Aop\Aop not exist in /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Bean/Container.php:75
Stack trace:
#0 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Bean/BeanFactory.php(76): Swoft\Bean\Container->get('Swoft\\Aop\\Aop')
#1 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Core/ApplicationContext.php(86): Swoft\Bean\BeanFactory::getBean('Swoft\\Aop\\Aop')
#2 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/App.php(124): Swoft\Core\ApplicationContext::getBean('Swoft\\Aop\\Aop')
#3 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Helper/Functions.php(97): Swoft\App::getBean('Swoft\\Aop\\Aop')
#4 /home/ubuntu/game_console/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(41): bean('Swoft\\Aop\\Aop')
x¸ⴇ¬homeµ㴇 ntu/game_console/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handl!ª

**Comment by yanwuguangjun** [comment]
已经确认是php 的redis 扩展没装  以为装了  hiredis  就可以了 看了下 代码 http 请求的redis 客户端 和websocket  请求时 使用的redis  不一样  
![image](https://user-images.githubusercontent.com/17357142/51401204-2b25ab00-1b85-11e9-924b-779845f519bd.png)
感觉官方对这个地方可以再文档里做个备注

**Comment by inhere** [comment]
(⊙o⊙)哦 。。。 想起来了，on open 是不在协程环境里的

**Comment by yanwuguangjun** [comment]
这个地方 会要调整吗
从字面上理解是不是 说  这里使用的不是一个Redis  连接池

**Comment by inhere** [comment]
open 这里是同步环境了。 使用的是 redis 扩展，不是 swoole 内置的客户端了

**Comment by yanwuguangjun** [comment]
可是swoole  提供的webosocket   server 不是异步非阻塞的吗 为什么onopen  是同步的？
