### ISSUE TITLE
当@Bean("crontab") 在init() 里使用config()报错

### ISSUE THREAD

**Issue by jlzan1314** [swoft-cloud/swoft#717]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.1
| Swoole version      | 4.4.0-alpha
| PHP version         | 7.1.20
| Runtime environment | CentOS 7

**Details**

当@bean("crontab") 在init() 里使用config()报错

```php
ic    | Fatal error: Uncaught Swoft\Bean\Exception\ContainerException: The singleton bean "config" is not defined in /home/wwwroot/swoft/vendor/swoft/bean/src/Container.php:488
ic    | Stack trace:
ic    | #0 /home/wwwroot/swoft/vendor/swoft/bean/src/BeanFactory.php(89): Swoft\Bean\Container->getSingleton('config')
ic    | #1 /home/wwwroot/swoft/vendor/swoft/framework/src/Helper/Functions.php(98): Swoft\Bean\BeanFactory::getSingleton('config')
ic    | #2 /home/wwwroot/swoft/packages/traceint-libs/src/Crontab/Crontab.php(56): config('cron.tasks', Array)
ic    | #3 /home/wwwroot/swoft/packages/traceint-libs/src/Crontab/Crontab.php(45): Traceint\Crontab\Crontab->initTasks()
ic    | #4 /home/wwwroot/swoft/vendor/swoft/bean/src/Container.php(911): Traceint\Crontab\Crontab->init()
ic    | #5 /home/wwwroot/swoft/vendor/swoft/bean/src/Container.php(793): Swoft\Bean\Container->newBean('crontab')
ic    | #6 /home/wwwroot/swoft/vendor/swoft/bean/src/Container.php(307): Swoft\Bean\Container->initializeBeans()
ic    | #7 /home/wwwroot/swoft/vendor/swoft/bean/src/BeanFactory.php(28): Swoft\Bean\Container->init()
```

```php
/**
 * Class Crontab
 * @Bean("crontab")
 */
class Crontab
{
    /**
     * @const 任务未执行态
     */
    const NORMAL = 0;

    /**
     * @const 任务完成态
     */
    const FINISH = 1;

    /**
     * @const 任务运行态
     */
    const START = 2;

    /**
     * @var array $task corntab任务
     */
    private $task;

    /**
     * 创建配置表
     *
     * @return bool
     */
    public function init()
    {
       config('xxx.xxx')
    }
}
```
```php
    /**
     * 我是这样解决的,不知道行不行
     *
     * @param string $name
     *
     * @return object|mixed
     * @throws ContainerException
     */
    public function getSingleton(string $name)
    {
        if (isset($this->singletonPool[$name])) {
            return $this->singletonPool[$name];
        }

        if (isset($this->aliases[$name])) {
            $name = $this->aliases[$name];
            return $this->singletonPool[$name];
        }

        $classNames = $this->classNames[$name] ?? [];
        if ($classNames) {
            $name = end($classNames);
            return $this->singletonPool[$name];
        }

	if (isset($this->objectDefinitions[$name]) && $this->objectDefinitions[$name]->getScope()==Bean::SINGLETON) {
		    return $this->get($name);
        }

        throw new ContainerException(sprintf('The singleton bean "%s" is not defined', $name));
    }

```

**Comment by stelin** [comment]
@jlzan1314 已修复，2.0.2版本
