### ISSUE TITLE
URI解析错误

### ISSUE THREAD

**Issue by jlzan1314** [swoft-cloud/swoft#730]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.2
| Swoole version      | 4.4.4
| PHP version         | php 7.1.20
| Runtime environment | Ubuntu

> URI解析错误

```php
$uri=Uri::new("http://www.163.com");
$uri->getQuery() 在php严格模式下报错
url没有query的情况下,解析时候

   public function getQuery(): string
    {
        // Init on get
        if ('' === $this->query) {
            // $this->query = $this->params['query'];
            $this->query = $this->filterQueryAndFragment( $this->params['query']??"");
        }

        return $this->query;
    }

params["query"] 未定义直接使用了..加??号就可以了或者isset()就可以了

```
```
#0 /home/wwwroot/swoft/vendor/swoft/http-message/src/Uri/Uri.php(318): Swoft\\Error\\DefaultErrorDispatcher->handleError(8, 'Undefined index...', '/home/wwwroot/s...', 318, Array)\n
#1 /home/wwwroot/swoft/packages/traceint-libs/src/Http/SwooleHttpClient.php(41): Swoft\\Http\\Message\\Uri\\Uri->getQuery()\n
```

**Comment by jlzan1314** [comment]
仔细测试是没有指定异常句柄参数导致的
```
/**
     * Register system error handle
     *
     * @throws InvalidArgumentException
     */
    protected function registerErrorHandle(): void
    {
        set_error_handler([$this, 'handleError'],E_ALL ^ E_NOTICE);
        set_exception_handler([$this, 'handleException']);
        register_shutdown_function(function () {
            if (!$e = error_get_last()) {
                return;
            }

            $this->handleError($e['type'], $e['message'], $e['file'], $e['line']);
        });
    }
指定了E_ALL ^ E_NOTICE 就正确了,不然每次读取数组的时候,index 不存在就会抛异常,这个异常是我不想要的,而且框架的代码有时候运行也有问题,建议加个配置,如果想用的,可以自行设置,,这个改为默认设置
```

**Comment by inhere** [comment]
uri 这里我做下兼容处理

> 😄 建议处理所有错误
