### ISSUE TITLE
验证器的message

### ISSUE THREAD

**Issue by ChangeChe** [swoft-cloud/swoft#796]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | v2.0.2
| Swoole version      | 4.3.1
| PHP version         | 7.2.16
| Runtime environment | Docker

**Details**

> 验证注解@NotEmpty，填写message后没有生效

```php
/**
     * @IsArray()
     * @NotEmpty(message="账号不能为空")
     *
     * @var array
     */
    protected $accounts;
```
```
返回错误
{
    "code": 0,
    "error": "(Swoft\\Validator\\Exception\\ValidatorException) accounts must exist!",
    "file": "At /home/www/user_center/vendor/swoft/validator/src/Concern/ValidateItemTrait.php line 56",
    "trace": "#0 /home/www/user_center/vendor/swoft/validator/src/Validator.php(213): Swoft\\Validator\\Validator->validateIsArray(Array, 'accounts', Object(Swoft\\Validator\\Annotation\\Mapping\\IsArray), NULL)\n#1 /home/www/user_center/vendor/swoft/validator/src/Validator.php(190): Swoft\\Validator\\Validator->validateDefaultItem(Array, 'accounts', Object(Swoft\\Validator\\Annotation\\Mapping\\IsArray), NULL)\n#2 /home/www/user_center/vendor/swoft/validator/src/Validator.php(159): Swoft\\Validator\\Validator->validateDefaultValidator(Array, Array, Array)\n#3 /home/www/user_center/vendor/swoft/validator/src/Validator.php(128): Swoft\\Validator\\Validator->validateValidator(Array, 1, 'userValidator', Array, Array, Array)\n#4 /home/www/user_center/vendor/swoft/http-server/src/Middleware/ValidatorMiddleware.php(73): Swoft\\Validator\\Validator->validateRequest(Array, Array, Array)\n#5 /home/www/user_center/vendor/swoft/http-server/src/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\ValidatorMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#6 /home/www/user_center/app/Http/Middleware/AuthorizeMiddleware.php(49): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#7 /home/www/user_center/vendor/swoft/http-server/src/RequestHandler.php(75): App\\Http\\Middleware\\AuthorizeMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#8 /home/www/user_center/app/Http/Middleware/JwtDecodeMiddleware.php(56): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#9 /home/www/user_center/vendor/swoft/http-server/src/RequestHandler.php(75): App\\Http\\Middleware\\JwtDecodeMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#10 /home/www/user_center/vendor/swoft/http-server/src/Middleware/UserMiddleware.php(56): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#11 /home/www/user_center/vendor/swoft/http-server/src/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#12 /home/www/user_center/vendor/swoft/http-server/src/HttpDispatcher.php(77): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#13 /home/www/user_center/vendor/swoft/http-server/src/Swoole/RequestListener.php(38): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#14 {main}"
}
```

**Comment by stelin** [comment]
@ChangeChe 

accounts must exist!  错误已经说明了，你这个字段都没有，先是验证字段是否存在，在验证内容

**Comment by ChangeChe** [comment]
@stelin 我在NotEmpty这个注释里有加message。正常情况不应该是提示我message里填写的内容吗？

**Comment by ChangeChe** [comment]
@stelin 那怎么改must exist这个提示呢？

**Comment by stelin** [comment]
@ChangeChe 文档有介绍，很详细

**Comment by ChangeChe** [comment]
... 这个不看源码还真看不出来

**Comment by inhere** [comment]
感觉文档有遗漏的 可以帮忙补充下
