### ISSUE TITLE
在Dao层Inject Redis失败

### ISSUE THREAD

**Issue by lingxiaoda** [swoft-cloud/swoft#897]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.4
| Swoole version      | 4.4.3
| PHP version         | 7.2.18
| Runtime environment | CentOS 7

**Details**

> 在控制器可以使用Inject redis连接池，但是在dao层的启动服务直接报错
是因为Dao层不支持这样子的写法吗？

```php
启动rpc：
php bin/swoft rpc:start
控制台显示
2019/08/15-13:02:20 [INFO] Swoft\Processor\AnnotationProcessor:handle(45) Annotations is scanned(autoloader 29, annotation 318, parser 64)
PHP Fatal error:  Uncaught Swoft\Annotation\Exception\AnnotationException: Property or method(App\Model\Dao\TokenDao) with `@xxx` must be define class annotation in /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php:113
Stack trace:
#0 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php(93): Swoft\Bean\Definition\Parser\AnnotationObjParser->parseOneClassAnnotations('App\\Model\\Dao\\T...', Array)
#1 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Container.php(649): Swoft\Bean\Definition\Parser\AnnotationObjParser->parseAnnotations(Array, Array)
#2 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Container.php(302): Swoft\Bean\Container->parseAnnotations()
#3 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/BeanFactory.php(28): Swoft\Bean\Container->init()
#4 /www/wwwroot/user.rpc.com/vendor/swoft/framework/src/Processor/BeanProcessor.php(52): Swoft\Bean\BeanFactory::init()
#5 /www/wwwroot/user.rpc.com/vendor/swoft/framework/src/Processor/ApplicationPro in /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php on line 113

Fatal error: Uncaught Swoft\Annotation\Exception\AnnotationException: Property or method(App\Model\Dao\TokenDao) with `@xxx` must be define class annotation in /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php:113
Stack trace:
#0 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php(93): Swoft\Bean\Definition\Parser\AnnotationObjParser->parseOneClassAnnotations('App\\Model\\Dao\\T...', Array)
#1 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Container.php(649): Swoft\Bean\Definition\Parser\AnnotationObjParser->parseAnnotations(Array, Array)
#2 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Container.php(302): Swoft\Bean\Container->parseAnnotations()
#3 /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/BeanFactory.php(28): Swoft\Bean\Container->init()
#4 /www/wwwroot/user.rpc.com/vendor/swoft/framework/src/Processor/BeanProcessor.php(52): Swoft\Bean\BeanFactory::init()
#5 /www/wwwroot/user.rpc.com/vendor/swoft/framework/src/Processor/ApplicationPro in /www/wwwroot/user.rpc.com/vendor/swoft/bean/src/Definition/Parser/AnnotationObjParser.php on line 113
```

> Provide minimal script to reproduce the issue

```php
TokenDao.php
<?php declare(strict_types=1);


namespace App\Model\Dao;

use App\Exception\TokenException;
use App\Model\Entity\Token;
use Swoft\Bean\Annotation\Mapping\Inject;
use Swoft\Redis\Pool;
use Swoft\Redis\Redis;

/**
 * Class TokenDao
 * @package App\Model\Dao
 */
class TokenDao
{
    protected $time;
    /**
     * @Inject()
     * 尝试了在Inject指定"redis.pool"也不行
     * @var Pool
     */
    private $redis;


    public function generateToken()
    {
        return $this->redis->set("token", uniqid());
    }

Bean.php配置文件
 'redis'      => [
        'class'         => RedisDb::class,
        'host'          => '127.0.0.1',
        'port'          => 6379,
        'database'      => 1,
        'retryInterval' => 10,
        'readTimeout'   => 0,
        'timeout'       => 2,
        'option'        => [
            'prefix'      => 'swoft:',
            'serializer' => Redis::SERIALIZER_PHP
        ],
    ],
    'redis.pool'     => [
        'class'   => \Swoft\Redis\Pool::class,
        'redisDb' => \bean('redis'),
        'minActive'   => 10,
        'maxActive'   => 20,
        'maxWait'     => 0,
        'maxWaitTime' => 0,
        'maxIdleTime' => 60,
    ],
```

**Comment by sakuraovq** [comment]
看文档 使用属性注解必须 有类注解

**Comment by xiaomemehe** [comment]
```
<?php declare(strict_types=1);

namespace App\Console\Command;

use Swoft\Console\Annotation\Mapping\Command;
use Swoft\Console\Annotation\Mapping\CommandMapping;

/**
 * @Command()
 */
class DemoCommand extends CommCommand
{
    /**
     * @CommandMapping()
     */
    public function test(): void
    {
        $this->tests();
        var_dump("test_demo");
    }
}

```

### DemoService
```
<?php declare(strict_types=1);
namespace App\Console\Command;

use App\Service\DemoService;
use Swoft\Bean\Annotation\Mapping\Inject;

class CommCommand
{
    /**
     * @Inject()
     * @var DemoService
     */
    private $d;
    public function tests() {
        $this->d->demo();
        var_dump("tests");
    }
}

```

### DemoService
```
<?php declare(strict_types=1);
namespace App\Service;

use Swoft\Bean\Annotation\Mapping\Bean;

/**
 * @package App\Service
 * @Bean(name="demoservice", scope=Bean::PROTOTYPE)
 */
class DemoService {
    public function demo() {
        var_dump("demo");
    }
}

```

**Comment by xiaomemehe** [comment]
* Demo继承一个父类，然后父类中使用inject注入一个bean，这个时候会报错，
* **with `@xxx` must be define class annotation**
* 父类中怎么处理
### DemoCommand

```
<?php declare(strict_types=1);

namespace App\Console\Command;

use Swoft\Console\Annotation\Mapping\Command;
use Swoft\Console\Annotation\Mapping\CommandMapping;

/**
 * @Command()
 */
class DemoCommand extends CommCommand
{
    /**
     * @CommandMapping()
     */
    public function test(): void
    {
        $this->tests();
        var_dump("test_demo");
    }
}

```

### CommCommand

```
<?php declare(strict_types=1);
namespace App\Console\Command;

use App\Service\DemoService;
use Swoft\Bean\Annotation\Mapping\Inject;

class CommCommand
{
    /**
     * @Inject()
     * @var DemoService
     */
    private $d;
    public function tests() {
        $this->d->demo();
        var_dump("tests");
    }
}

```

### DemoService
```
<?php declare(strict_types=1);
namespace App\Service;

use Swoft\Bean\Annotation\Mapping\Bean;

/**
 * @package App\Service
 * @Bean(name="demoservice", scope=Bean::PROTOTYPE)
 */
class DemoService {
    public function demo() {
        var_dump("demo");
    }
}

```

**Comment by xiaomemehe** [comment]
> * Demo继承一个父类，然后父类中使用inject注入一个bean，这个时候会报错，
> * **with `@xxx` must be define class annotation**
> * 父类中怎么处理
> 
> ### DemoCommand
> ```
> <?php declare(strict_types=1);
> 
> namespace App\Console\Command;
> 
> use Swoft\Console\Annotation\Mapping\Command;
> use Swoft\Console\Annotation\Mapping\CommandMapping;
> 
> /**
>  * @Command()
>  */
> class DemoCommand extends CommCommand
> {
>     /**
>      * @CommandMapping()
>      */
>     public function test(): void
>     {
>         $this->tests();
>         var_dump("test_demo");
>     }
> }
> ```
> 
> ### CommCommand
> ```
> <?php declare(strict_types=1);
> namespace App\Console\Command;
> 
> use App\Service\DemoService;
> use Swoft\Bean\Annotation\Mapping\Inject;
> 
> class CommCommand
> {
>     /**
>      * @Inject()
>      * @var DemoService
>      */
>     private $d;
>     public function tests() {
>         $this->d->demo();
>         var_dump("tests");
>     }
> }
> ```
> 
> ### DemoService
> ```
> <?php declare(strict_types=1);
> namespace App\Service;
> 
> use Swoft\Bean\Annotation\Mapping\Bean;
> 
> /**
>  * @package App\Service
>  * @Bean(name="demoservice", scope=Bean::PROTOTYPE)
>  */
> class DemoService {
>     public function demo() {
>         var_dump("demo");
>     }
> }
> ```

提示的错误信息是，使用属性注解必须有类注解，，问题是父类中应该不需要有类注解的么？不懂求解
