### ISSUE TITLE
swoft 2.0.5 @PointExecution error

### ISSUE THREAD

**Issue by AridanJohn** [swoft-cloud/swoft#915]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.2
| PHP version         | 7.2.6
| Runtime environment | Docker etc.

## code ##
```
<?php declare(strict_types=1);


namespace App\Aspect;
use App\Exception\ApiException;
use phpDocumentor\Reflection\DocBlock\Tags\Throws;
use Swoft\Aop\Annotation\Mapping\After;
use Swoft\Aop\Annotation\Mapping\AfterReturning;
use Swoft\Aop\Annotation\Mapping\AfterThrowing;
use Swoft\Aop\Annotation\Mapping\Aspect;
use Swoft\Aop\Annotation\Mapping\Before;
use Swoft\Aop\Annotation\Mapping\PointBean;
use Swoft\Aop\Annotation\Mapping\PointExecution;
use Swoft\Aop\Point\JoinPoint;
use App\Http\Controller\Api\UserController;

/**
 * class UserAspect
 * @Aspect(order=1)
 * @PointExecution(
 *     include={
 *     "App\Http\Controller\Api\UserController::login.*",
 *     }
 * )
 * @since 2.0
 */
class UserAspect
 ```
## error ##
```
Warning: preg_match(): Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u at offset 24 in /var/www/swoft/vendor/swoft/aop/src/Aop.php on line 160
2019/08/23-14:07:13 [ERROR] Swoft\Error\DefaultExceptionHandler:handle(36) (DEFAULT HANDLER)Exception(ErrorException): preg_match(): Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u at offset 24
At File /var/www/swoft/vendor/swoft/aop/src/Aop.php line 160
Trace:
#0 [internal function]: Swoft\Error\DefaultErrorDispatcher->handleError(2, 'preg_match(): C...', '/var/www/swoft/...', 160, Array)
#1 /var/www/swoft/vendor/swoft/aop/src/Aop.php(160): preg_match('/App\\Http\\Contr...', 'Swoft\\Error\\Err...')
#2 /var/www/swoft/vendor/swoft/aop/src/Aop.php(75): Swoft\Aop\Aop::isExecution('Swoft\\Error\\Err...', 'addHandler', Array)
#3 /var/www/swoft/vendor/swoft/framework/src/BeanHandler.php(95): Swoft\Aop\Aop::register(Array, 'Swoft\\Error\\Err...', 'addHandler', Array)
#4 /var/www/swoft/vendor/swoft/bean/src/Container.php(1100): Swoft\BeanHandler->beforeInit('Swoft\\Error\\Err...', 'Swoft\\Error\\Err...', Object(Swoft\Bean\Definition\ObjectDefinition), Array)
#5 /var/www/swoft/vendor/swoft/bean/src/Container.php(904): Swoft\Bean\Container->beforeInit('Swoft\\Error\\Err...', 'Swoft\\Error\\Err...', Object(Swoft\Bean\Definition\ObjectDefinition))
#6 /var/www/swoft/vendor/swoft/bean/src/Container.php(793): Swoft\Bean\Container->newBean('Swoft\\Error\\Err...')
#7 /var/www/swoft/vendor/swoft/bean/src/Container.php(308): Swoft\Bean\Container->initializeBeans()
#8 /var/www/swoft/vendor/swoft/bean/src/BeanFactory.php(26): Swoft\Bean\Container->init()
#9 /var/www/swoft/vendor/swoft/framework/src/Processor/BeanProcessor.php(50): Swoft\Bean\BeanFactory::init()
#10 /var/www/swoft/vendor/swoft/framework/src/Processor/ApplicationProcessor.php(34): Swoft\Processor\BeanProcessor->handle()
#11 /var/www/swoft/vendor/swoft/framework/src/SwoftApplication.php(219): Swoft\Processor\ApplicationProcessor->handle()
#12 /var/www/swoft/bin/swoft(12): Swoft\SwoftApplication->run()
#13 {main}


```

**Comment by inhere** [comment]
试试：

```php
  include={
 *     "App\\Http\\Controller\\Api\\UserController::login.*",
 *     }
```

**Comment by stelin** [comment]
@AridanJohn 你使用方式不对，斜杆需要转义
