### ISSUE TITLE
Return value of Swoft\Session\SessionManager::getSession() 

### ISSUE THREAD

**Issue by donglf681** [swoft-cloud/swoft#945]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.x
| Swoole version      | 4.3.3(by `php --ri swoole`)
| PHP version         | 7.2.15 (by `php -v`)
| Runtime environment | Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.
按照文档配置swoft session，但使用session()函数获取时就会提示
```
PHP Fatal error:  Uncaught TypeError: Return value of Swoft\Session\SessionManager::getSession() must implement interface Swoft\Session\SessionInterface, null returned in /var/www/vendor/swoft/session/src/SessionManager.php:99
Stack trace:
#0 /var/www/vendor/swoft/session/src/Helper/Functions.php(12): Swoft\Session\SessionManager->getSession()
#1 /var/www/vendor/carpcai/swoft-captcha/src/Captcha.php(102): session()
#2 /var/www/app/Commands/TestCommand.php(37): CarpCai\Captcha\Captcha->check('tttttttt')
#3 /var/www/vendor/swoft/framework/src/Helper/PhpHelper.php(47): App\Commands\TestCommand->debug()
#4 /var/www/vendor/swoft/console/src/Router/HandlerAdapter.php(96): Swoft\Helper\PhpHelper::call(Array, Array)
#5 /var/www/vendor/swoft/framework/src/Helper/PhpHelper.php(44): Swoft\Console\Router\HandlerAdapter->Swoft\Console\Router\{closure}()
#6 /var/www/vendor/swoft/framework/src/Core/Coroutine.php(73): Swoft\Helper\PhpHelper::call(Object(Closure))
#7 {main}
  thrown in /var/www/vendor/swoft/session/src/SessionManager.php on line 99

```
```
'serverDispatcher' => [
        'middlewares' => array_filter([
            env('MIDDLEWARE_DEV_TOOL'),
            env('MIDDLEWARE_SIGN'),
            \Swoft\Auth\Middleware\AuthMiddleware::class,
            \App\Middlewares\CorsMiddleware::class,
            \Swoft\Session\Middleware\SessionMiddleware::class,
        ])
    ],
    // 注意Bean大小写
    'sessionManager' => [
        'class' => \Swoft\Session\SessionManager::class,
        'config' => [
            'driver' => 'redis',
            'name' => 'SWOFT_SESSION_ID',
            'lifetime' => 120,
            'expire_on_close' => false,
            'encrypt' => false,
            'storage' => '@runtime/sessions',
        ],
    ],
```
请教下，哪边出问题？

**Comment by stelin** [comment]
建议升级到2.0

这应该是你配置问题

**Comment by donglf681** [comment]
我配置文件附上去了，哪里出问题了呢？
